#!/usr/bin/sh

# Options
DRIVE="sda"
PASSWORD=""

partition_disk() {
  (
  # creates gpt partition
  echo g; 
  # creates efi partition with size of 200MiB at sda1
  echo n; echo ""; echo ""; 
  echo "+200MiB"; 
  echo t; echo "1"; 
  # creates boot partition with size of 200MiB
  echo n; echo ""; echo ""; 
  echo "+800MiB"; echo t; 
  echo ""; echo "4"; 
  # creates filesystem partition with remaining storage
  echo n; echo ""; echo ""; echo "";
  # writes
  echo w;
  ) | sudo fdisk /dev/$DRIVE

}

mk_filesystem() {
  mkfs.vfat -nBOOT -F32 /dev/sda1 
  echo "y" | mkfs.ext2 -L grub /dev/sda2
  echo -n "$PASSWORD" | cryptsetup luksFormat --type=luks -s=512 /dev/sda3
  cryptsetup open /dev/sda3 cryptroot
  mkfs.btrfs -L void --force /dev/mapper/cryptroot
}

mount_partitions() {
  BTRFS_OPTS="rw,noatime,ssd,compress=zsdt,space_cache,commit=120"
  # creating subvols
  mount -o $BTRFS_OPTS /dev/mapper/cryptroot /mnt
  btrfs subvolume create /mnt/@
  btrfs subvolume create /mnt/@home
  btrfs subvolume create /mnt/@snapshots
  umount /mnt
  # mounting partitions
  mount -o $BTRFS_OPTS,subvol=0 /dev/mapper/cryptroot /mnt # /
  mkdir -p /mnt/home
  mount -o $BTRFS_OPTS,subvol=@home /dev/mapper/cryptroot /mnt/home # /home
  mkdir -p /mnt/.snapshots
  mount -o $BTRFS_OPTS,subvol=@snapshots /dev/mapper/cryptroot /mnt/.snapshots # /.snapshots
  mkdir -p /mnt/var/cache
  # mount nested partitions so they get snapshots
  btrfs subvolume create /mnt/var/cache/xbps
  btrfs subvolume create /mnt/var/tmp
  btrfs subvolume create /mnt/srv
  # nested subvolume for swap
  btrfs subvolume create /mnt/var/swap
  # mount efi partition
  mkdir /mnt/efi
  mount -o rw,noatime /dev/sda1 /mnt/efi
  # mount boot partition
  mkdir /mnt/efi
  mount -o rw,noatime /dev/sda2 /mnt/boot
}

echo "PARTITIONING DISKS"
partition_disk
echo "MAKING ENCRYPTED FILESYSTEM"
mk_filesystem
echo "MOUNTING PARTITIONS"
mount_partitions
